import type { Metadata } from 'next'
import './globals.css'
import { Rubik } from 'next/font/google'
import { ThemeProvider } from "@/components/theme-provider"
import { cn } from '@/components/shadcn'

const inter = Rubik({ subsets: ['cyrillic'], preload:true })

export const metadata: Metadata = {
  title: 'Apex Clinic',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {  

  const bodyClassName = cn(inter.className, 'flex flex-col h-full');

  return (
    <html lang="en" suppressHydrationWarning className='h-full'>
      <body className={bodyClassName} >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}